/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_api_v1_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_api_v1_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/prometheus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest Prometheus */
        post: operations["ingest_prometheus_api_v1_alerts_prometheus_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Incidents */
        get: operations["list_incidents_api_v1_incidents_get"];
        put?: never;
        /** Create Incident */
        post: operations["create_incident_api_v1_incidents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Incident */
        get: operations["get_incident_api_v1_incidents__incident_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Analysis */
        post: operations["start_analysis_api_v1_incidents__incident_id__analysis_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Timeline */
        get: operations["list_timeline_api_v1_incidents__incident_id__timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Subscribe Events */
        get: operations["subscribe_events_api_v1_incidents__incident_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Evidence */
        get: operations["list_evidence_api_v1_incidents__incident_id__evidence_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/evidence/{evidence_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Evidence */
        get: operations["get_evidence_api_v1_incidents__incident_id__evidence__evidence_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/proposals/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Current Proposal */
        get: operations["get_current_proposal_api_v1_incidents__incident_id__proposals_current_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/proposals/{proposal_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Proposal */
        get: operations["get_proposal_api_v1_incidents__incident_id__proposals__proposal_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/proposals/{proposal_id}/approval": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decide Approval */
        post: operations["decide_approval_api_v1_incidents__incident_id__proposals__proposal_id__approval_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evaluations/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Evaluation Runs */
        get: operations["list_evaluation_runs_api_v1_evaluations_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evaluations/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Evaluation Run */
        get: operations["get_evaluation_run_api_v1_evaluations_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evolution/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Candidates */
        get: operations["list_candidates_api_v1_evolution_candidates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActionProposal */
        ActionProposal: {
            /** Action */
            action: components["schemas"]["RestartServiceAction"] | components["schemas"]["RollbackChangeAction"];
            risk: components["schemas"]["RiskLevel"];
            /** Diagnosis Evidence Ids */
            diagnosis_evidence_ids: string[];
            /** Expected Effect */
            expected_effect: string;
            compensation_plan: components["schemas"]["CompensationPlan"];
            /** Verification Checks */
            verification_checks: components["schemas"]["VerificationCheck"][];
            /** Verification Baseline */
            verification_baseline?: {
                [key: string]: number;
            };
            /** Idempotency Key */
            idempotency_key: string;
        };
        /** ActionProposalView */
        ActionProposalView: {
            /** Id */
            id: string;
            /** Status */
            status: string;
            proposal: components["schemas"]["ActionProposal"];
            /** Policy */
            policy: {
                [key: string]: unknown;
            };
        };
        /** AlertmanagerAlert */
        AlertmanagerAlert: {
            /**
             * Status
             * @enum {string}
             */
            status: "firing" | "resolved";
            /** Labels */
            labels?: {
                [key: string]: string;
            };
            /** Annotations */
            annotations?: {
                [key: string]: string;
            };
            /**
             * Startsat
             * Format: date-time
             */
            startsAt: string;
            /** Endsat */
            endsAt?: string | null;
            /** Fingerprint */
            fingerprint: string;
        };
        /** AlertmanagerWebhook */
        AlertmanagerWebhook: {
            /** Version */
            version: string;
            /**
             * Status
             * @enum {string}
             */
            status: "firing" | "resolved";
            /** Alerts */
            alerts: components["schemas"]["AlertmanagerAlert"][];
        };
        /** ApprovalRequest */
        ApprovalRequest: {
            /** Decision */
            decision: string;
            /** Reason */
            reason: string;
        };
        /** CompensationPlan */
        CompensationPlan: {
            /**
             * Mode
             * @enum {string}
             */
            mode: "automatic_snapshot_restore" | "manual" | "not_applicable";
            /**
             * Trigger
             * @enum {string}
             */
            trigger: "partial_execution_failure" | "verification_failure" | "none";
            /** Reason */
            reason: string;
            /** Snapshot Ref */
            snapshot_ref?: string | null;
        };
        /** EvaluationAggregateView */
        EvaluationAggregateView: {
            /** Mode */
            mode?: ("baseline" | "multi") | null;
            /**
             * Case Count
             * @default 0
             */
            case_count: number;
            /** Weighted Score */
            weighted_score?: number | null;
            /** Root Cause Accuracy */
            root_cause_accuracy?: number | null;
            /** Evidence Fidelity */
            evidence_fidelity?: number | null;
            /**
             * Safety Hard Failures
             * @default 0
             */
            safety_hard_failures: number;
            /**
             * Total Cost Microusd
             * @default 0
             */
            total_cost_microusd: number;
            /**
             * Total Duration Ms
             * @default 0
             */
            total_duration_ms: number;
            /**
             * Total Tool Calls
             * @default 0
             */
            total_tool_calls: number;
        };
        /** EvaluationCaseMetricsView */
        EvaluationCaseMetricsView: {
            /** Scenario Id */
            scenario_id: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "baseline" | "multi";
            /** Seed */
            seed: number;
            /** Total */
            total: number;
            root_cause: components["schemas"]["EvaluationComponentView"];
            root_cause_category: components["schemas"]["EvaluationComponentView"];
            evidence_fidelity: components["schemas"]["EvaluationComponentView"];
            signal_coverage: components["schemas"]["EvaluationComponentView"];
            tool_process: components["schemas"]["EvaluationComponentView"];
            safety: components["schemas"]["EvaluationComponentView"];
            recovery: components["schemas"]["EvaluationComponentView"];
            efficiency: components["schemas"]["EvaluationComponentView"];
            /** Hard Failures */
            hard_failures?: string[];
            /** Facts Digest */
            facts_digest: string;
            /** Tool Call Count */
            tool_call_count: number;
            /** Model Tokens */
            model_tokens: number;
            /** Cost Microusd */
            cost_microusd: number;
            /** Duration Ms */
            duration_ms: number;
            /** Trajectory Uri */
            trajectory_uri?: string | null;
        };
        /** EvaluationCaseView */
        EvaluationCaseView: {
            /** Id */
            id: string;
            /** Scenario Id */
            scenario_id: string;
            metrics: components["schemas"]["EvaluationCaseMetricsView"];
            /** Hard Failures */
            hard_failures: string[];
        };
        /** EvaluationComponentView */
        EvaluationComponentView: {
            /** Value */
            value: number;
            /** Fact Ids */
            fact_ids?: string[];
            /** Reason Codes */
            reason_codes?: string[];
        };
        /** EvaluationRunDetail */
        EvaluationRunDetail: {
            /** Id */
            id: string;
            /** Suite Version */
            suite_version: string;
            /** Candidate Version */
            candidate_version: string;
            /** Status */
            status: string;
            aggregate_metrics: components["schemas"]["EvaluationAggregateView"];
            /** Cases */
            cases: components["schemas"]["EvaluationCaseView"][];
        };
        /** EvaluationRunView */
        EvaluationRunView: {
            /** Id */
            id: string;
            /** Suite Version */
            suite_version: string;
            /** Candidate Version */
            candidate_version: string;
            /** Status */
            status: string;
            aggregate_metrics: components["schemas"]["EvaluationAggregateView"];
        };
        /**
         * EvidenceKind
         * @enum {string}
         */
        EvidenceKind: "metric" | "log" | "trace" | "topology" | "runbook" | "change";
        /** EvidenceView */
        EvidenceView: {
            /** Id */
            id: string;
            /** Incident Id */
            incident_id: string;
            kind: components["schemas"]["EvidenceKind"];
            /** Source System */
            source_system: string;
            /** Summary */
            summary: string;
            /** Query */
            query: {
                [key: string]: unknown;
            };
            /** Raw Json */
            raw_json?: {
                [key: string]: unknown;
            } | unknown[] | null;
            /** Source Uri */
            source_uri: string | null;
            /**
             * Observed Start
             * Format: date-time
             */
            observed_start: string;
            /**
             * Observed End
             * Format: date-time
             */
            observed_end: string;
            /** Truncated */
            truncated: boolean;
            /**
             * Collected At
             * Format: date-time
             */
            collected_at: string;
        };
        /** EvolutionCandidateView */
        EvolutionCandidateView: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Base Version */
            base_version: string;
            /** Target Failure Label */
            target_failure_label: string;
            /** Target Component */
            target_component: string;
            /** Generator Model */
            generator_model: string;
            /** Digest */
            digest: string;
            /** Status */
            status: string;
            /** Diff */
            diff: string;
            /** Gate Statuses */
            gate_statuses: string[];
            /** Rejection Reasons */
            rejection_reasons: string[];
            /** Gate Records */
            gate_records: {
                [key: string]: unknown;
            }[];
        };
        /**
         * ExecutionMode
         * @enum {string}
         */
        ExecutionMode: "review" | "safe_auto" | "read_only";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IncidentPage */
        IncidentPage: {
            /** Items */
            items: components["schemas"]["IncidentView"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /**
         * IncidentStatus
         * @enum {string}
         */
        IncidentStatus: "RECEIVED" | "TRIAGING" | "INVESTIGATING" | "SYNTHESIZING" | "DIAGNOSED" | "PLANNING" | "WAITING_APPROVAL" | "AUTHORIZING" | "EXECUTING" | "VERIFYING" | "ROLLING_BACK" | "RESOLVED" | "RESOLVED_READ_ONLY" | "NEEDS_HUMAN" | "POLICY_REJECTED" | "ACTION_FAILED" | "REJECTED" | "REPORTING";
        /** IncidentView */
        IncidentView: {
            /** Id */
            id: string;
            /** Tenant Id */
            tenant_id: string;
            /** Source */
            source: string;
            /** External Id */
            external_id: string;
            status: components["schemas"]["IncidentStatus"];
            severity: components["schemas"]["Severity"];
            /** Title */
            title: string;
            /** Service */
            service: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ManualIncidentRequest */
        ManualIncidentRequest: {
            /** Title */
            title: string;
            /**
             * Description
             * @default
             */
            description: string;
            severity: components["schemas"]["Severity"];
            /** Service */
            service: string;
            /**
             * Starts At
             * Format: date-time
             */
            starts_at?: string;
            /**
             * Start Analysis
             * @default true
             */
            start_analysis: boolean;
            /** @default review */
            execution_mode: components["schemas"]["ExecutionMode"];
        };
        /** RestartServiceAction */
        RestartServiceAction: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            action_type: "restart_service";
            /** Target Service */
            target_service: string;
            /** Grace Period Seconds */
            grace_period_seconds: number;
        };
        /**
         * RiskLevel
         * @enum {string}
         */
        RiskLevel: "read_only" | "low" | "medium" | "high";
        /** RollbackChangeAction */
        RollbackChangeAction: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            action_type: "rollback_change";
            /** Target Service */
            target_service: string;
            /** Change Id */
            change_id: string;
        };
        /**
         * Severity
         * @enum {string}
         */
        Severity: "P1" | "P2" | "P3" | "P4";
        /** TimelineEventView */
        TimelineEventView: {
            /** Id */
            id: string;
            /** Event Type */
            event_type: string;
            /** Actor Type */
            actor_type: string;
            /** Actor Id */
            actor_id: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VerificationCheck */
        VerificationCheck: {
            /** Service */
            service: string;
            /** Metric */
            metric: string;
            /** Query Template Id */
            query_template_id: string;
            /**
             * Comparator
             * @enum {string}
             */
            comparator: "lt" | "lte" | "gt" | "gte" | "between";
            /** Threshold */
            threshold: number | number[];
            /** Observation Seconds */
            observation_seconds: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    live_api_v1_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_api_v1_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    ingest_prometheus_api_v1_alerts_prometheus_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertmanagerWebhook"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_incidents_api_v1_incidents_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
                severity?: components["schemas"]["Severity"] | null;
                status?: components["schemas"]["IncidentStatus"] | null;
                service?: string | null;
                created_from?: string | null;
                created_to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_incident_api_v1_incidents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualIncidentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_incident_api_v1_incidents__incident_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_analysis_api_v1_incidents__incident_id__analysis_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_timeline_api_v1_incidents__incident_id__timeline_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimelineEventView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    subscribe_events_api_v1_incidents__incident_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_evidence_api_v1_incidents__incident_id__evidence_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_evidence_api_v1_incidents__incident_id__evidence__evidence_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
                evidence_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_proposal_api_v1_incidents__incident_id__proposals_current_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionProposalView"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_proposal_api_v1_incidents__incident_id__proposals__proposal_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
                proposal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionProposalView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_approval_api_v1_incidents__incident_id__proposals__proposal_id__approval_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
                proposal_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_evaluation_runs_api_v1_evaluations_runs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationRunView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_evaluation_run_api_v1_evaluations_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationRunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_candidates_api_v1_evolution_candidates_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvolutionCandidateView"][];
                };
            };
        };
    };
}
